### PR TITLE
D8CORE-1519: Update counter.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Adds an update for the tab and bubble.

# Needed By (Date)
- Meh

# Urgency
- Low

### CODE REVIEW

**Review by pookmish — APPROVED** [review]
Ooh yeah that totally makes sense. good thinking. Got some failing tests now though

**Comment by sherakama** [comment]
> Ooh yeah that totally makes sense. good thinking. Got some failing tests now though

I was looking for an AjaxResponse that just updated an HTML property of the selector but that doesn't seem to exist. I may refactor this to a javascript callback and add the middle man function to update the HTML property.

**Comment by pookmish** [comment]
I think what you really want is the `InvokeCommand` https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Ajax%21InvokeCommand.php/class/InvokeCommand

> Intended for simple jQuery commands, such as attr(), addClass(), removeClass(), toggleClass(), etc.

**Comment by pookmish** [comment]
https://github.com/SU-SWS/stanford_notifications/pull/3

**Comment by sherakama** [comment]
Now we just need some styles.

**Comment by pookmish** [comment]
like this? style

**Pull request merged**
